lint.select = ["ALL"]
lint.fixable = ["ALL"]
lint.ignore = [
    "COM812",
    "D203",
    "D205",
    "D212",
    "D401",
    "D404",
    "PD004",
    "PD010",
    "PD013",
    "S314",
    "SIM115",
]
extend-include = ["*.ipynb"]
exclude = [
    ".eggs",
    ".git",
    ".venv",
    "__pypackages__",
    "build",
    "tests",
    "__init__.py",
    "test",
]

line-length = 120
indent-width = 4
